### ISSUE TITLE
Seems like sql file has bug

### ISSUE THREAD

**Issue by txya900619** [NPC-GO/MaJaJalist-backend#13]
NOOOOOOOO Wryyyyyyyyyyyyy

**Comment by txya900619** [comment]
noooo not fixd 
seems like varchar 100 in not enough 
I try to change type from varchar to text

**Comment by txya900619** [comment]
not workkkkk 
seems like "" is very important

**Comment by txya900619** [comment]
== "" real not work

**Comment by txya900619** [comment]
seem's need to change // : to %?

**Comment by Xanonymous-GitHub** [comment]
I is don't know

**Comment by txya900619** [comment]
Oh only need replace " to '
it is ok ok
